kind: Deployment
apiVersion: apps/v1
metadata:
  name: sensatronics-exporter
  labels:
    app: sensatronics-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sensatronics-exporter
  template:
    metadata:
      labels:
        app: sensatronics-exporter
    spec:
      containers:
        - name: sensatronics-exporter
          image: 14agerber/sensatronics_exporter:1.2-beta
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9862
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 9862
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9862
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5

---

kind: Service
apiVersion: v1
metadata:
  name: sensatronics-exporter
  labels:
    app: sensatronics-exporter
spec:
  ports:
    - port: 9862
      targetPort: 9862
  selector:
    app: sensatronics-exporter